# Generated by Django 4.2.29 on 2026-05-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this conversation belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='projects.project'),
        ),
    ]
