# Generated by Django 4.2.29 on 2026-04-25 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_name', models.CharField(blank=True, default='', help_text='What Clarix AI should call you?', max_length=50)),
                ('work_type', models.CharField(choices=[('student', 'Student'), ('developer', 'Developer'), ('designer', 'Designer'), ('researcher', 'Researcher'), ('writer', 'Writer'), ('marketer', 'Marketer'), ('manager', 'Manager'), ('entrepreneur', 'Entrepreneur'), ('other', 'Other')], default='other', max_length=20)),
                ('professional_preference', models.CharField(choices=[('beginner', 'Beginner - explain concepts simply'), ('intermediate', 'Intermediate - assume basic knowledge'), ('expert', 'Expert - use technical language')], default='intermediate', max_length=20)),
                ('notify_response_complete', models.BooleanField(default=True, help_text='Notify when AI response is complete')),
                ('notify_product_updates', models.BooleanField(default=True, help_text='Receive product update emails')),
                ('notify_billing_alerts', models.BooleanField(default=True, help_text='Receive billing and payment alerts')),
                ('appearance', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='auto', max_length=10)),
                ('allow_data_improvement', models.BooleanField(default=True, help_text='Allow conversations to improve Clarix AI')),
                ('allow_analytics', models.BooleanField(default=True, help_text='Allow anonymous usage analytics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
    ]
