# Generated by Django 4.2.29 on 2026-05-12 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('emoji', models.CharField(blank=True, default='📁', help_text='Emoji icon for the project', max_length=10)),
                ('color', models.CharField(blank=True, default='#5c6bc0', help_text='Hex color for project card', max_length=7)),
                ('is_archived', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0, help_text='Manual sort order - lower = first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
    ]
