# Generated by Django 4.2.29 on 2026-05-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='emoji',
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, default='folder', help_text='Project icon', max_length=50),
        ),
    ]
